# Generated by Django 2.2.5 on 2019-09-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='side',
            field=models.CharField(blank=True, max_length=12, verbose_name='side'),
        ),
    ]
