#!/bin/bash

while read oldrev newrev refname
do
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    if [ "master" == "$branch" ]; then
        mkdir -p /opt/venom
        cd /opt/venom
        sudo git --git-dir=/home/git/venom.git --work-tree=/opt/venom checkout -f master >/dev/null

        PIP=/home/luotao/venv/venom/bin/pip
        sudo ${PIP} install -r requirements.txt || exit 1
        sudo chown luotao /home/luotao/venv/venom -R
        sudo chown luotao /opt/venom -R

        sudo supervisorctl restart venom
    fi
done